language:
  - cpp

dist:
  - trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests

after_success:
  - coveralls --root .. -E ".*CMakeFiles.*" -E ".*tests.*"