language:
  - generic

dist:
  - trusty

env:
  - COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./alive_tests