language:
  - cpp

dist:
  - trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - g++-5

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./tests

after_success:
  - coveralls --root .. -E ".*CMakeFiles.*" -E ".*tests.*"